openapi: 3.0.1
info:
  title: CovidSafe
  version: 0.1.0
paths:
  /data/{id}:
    post:
      summary: Post location history
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Id of this location history
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                points:
                  type: array
                  items:
                    $ref: '#/components/schemas/point'
                id:
                  type: array
                  items:
                    type: string
      responses:
        200:
          description: default
          content: {}
components:
  schemas:
    point:
      type: object
      properties:
        lat:
          type: number
          format: float
        lng:
          type: number
          format: float
        time:
          type: integer
          format: int64

