openapi: 3.0.1
info:
  title: CovidSafe
  version: 0.1.0
servers:
- url: /
paths:
  /data/{id}:
    post:
      summary: Post location history
      operationId: dataIdPOST
      parameters:
      - name: id
        in: path
        description: Id of this location history
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/body'
        required: true
      responses:
        "200":
          description: default
          content: {}
      x-swagger-router-controller: Default
components:
  schemas:
    point:
      required:
      - lat
      - lng
      - time
      type: object
      properties:
        lat:
          type: number
          format: float
        lng:
          type: number
          format: float
        time:
          type: integer
          format: int64
    body:
      required:
      - points
      type: object
      properties:
        points:
          type: array
          items:
            $ref: '#/components/schemas/point'
